#!/bin/sh

mkdir -p /run/tmpfiles.d
test -f /run/tmpfiles.d/nvidia-logind-acl-trick-G06.conf && rm /run/tmpfiles.d/nvidia-logind-acl-trick-G06.conf || true
touch /run/tmpfiles.d/nvidia-logind-acl-trick-G06.conf
echo "L /run/udev/static_node-tags/uaccess/nvidiactl - - - - /dev/nvidiactl" >> /run/tmpfiles.d/nvidia-logind-acl-trick-G06.conf
echo "L /run/udev/static_node-tags/uaccess/nvidia-uvm - - - - /dev/nvidia-uvm" >> /run/tmpfiles.d/nvidia-logind-acl-trick-G06.conf
echo "L /run/udev/static_node-tags/uaccess/nvidia-uvm-tools - - - - /dev/nvidia-uvm-tools" >> /run/tmpfiles.d/nvidia-logind-acl-trick-G06.conf
echo "L /run/udev/static_node-tags/uaccess/nvidia-modeset - - - - /dev/nvidia-modeset" >> /run/tmpfiles.d/nvidia-logind-acl-trick-G06.conf
devid=-1
for dev in $(ls -d /sys/bus/pci/devices/*); do 
  vendorid=$(cat $dev/vendor)
  if [ "$vendorid" == "0x10de" ]; then 
    class=$(cat $dev/class)
    classid=${class%%00}
    if [ "$classid" == "0x0300" -o "$classid" == "0x0302" ]; then 
      devid=$((devid+1))
      echo "L /run/udev/static_node-tags/uaccess/nvidia${devid} - - - - /dev/nvidia${devid}" >> /run/tmpfiles.d/nvidia-logind-acl-trick-G06.conf
    fi
  fi
done
systemd-tmpfiles --create /run/tmpfiles.d/nvidia-logind-acl-trick-G06.conf
